services:
  # PHP (Laravel)
  php:
    build:
      context: ./app/back
      dockerfile: ../../docker/php/Dockerfile 
    container_name: php
    volumes:
      - ./app/back:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=app
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  # Node (Next.js)
  node:
    build:
      context: ./app/front
      dockerfile: ../../docker/node/Dockerfile 
    container_name: node
    volumes:
      - ./app/front:/app
    ports:
      - "3000:3000"
    command: "npm run dev"

  # Nginx（Laravel + Next.js のリバースプロキシ）
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./app/back:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node

  # MySQL
  db:
    image: mysql:8.3
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
